modLoader = "javafml"
loaderVersion = "${forge_loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "${issue_tracker_url}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
#updateJSONURL="${auto_update_url}"
#displayURL="${display_url}"
logoFile = "${mod_logo_path}"
credits = "${mod_credits}"
authors = "${mod_authors}"
description = '''${mod_description}'''

# Base
[[dependencies.${mod_id}]]
    modId = "forge"
    mandatory = true
    versionRange = "${forge_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    mandatory = true
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "bagus_lib"
mandatory = true
versionRange = "${bagus_lib_version_range}"
ordering = "NONE"
side = "BOTH"